version: "3.3"

networks:
   reactor:
     ipam:
       config:
         - subnet: 192.168.10.0/24

services:
  report_mysql:
    image: reactor-report-mysql:1.0
    command: --sql_mode=""
    networks:
      - reactor
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssword
      - MYSQL_DATABASE=reactor
      - MYSQL_USER=reactor
      - MYSQL_PASSWORD=p@ssword
    volumes:
      - $HOME/.reactor/db/:/var/lib/mysql

  report_nginx:
    image: reactor-report-nginx:1.0
    networks:
      - reactor
    ports:
      - "30080:80"
    volumes:
      - $HOME/.reactor/logs/:/usr/share/nginx/html/logs/

  report_tomee:
    image: reactor-report-tomee:1.2.11
    networks:
      - reactor
    ports:
      - "38080:8080"
