#!/bin/bash

#echo "install desktop"
#sudo apt-get update
#apt-get install -y --force-yes ubuntu-desktop


echo "install oracle java8"
# wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz
add-apt-repository ppa:webupd8team/java
apt-get update
echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
apt-get install -y oracle-java8-installer
apt-get install -y oracle-java8-set-default
java -version


echo "install mysql"
DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes install mysql-server
sed -i '/bind-address/d' /etc/mysql/my.cnf

cat <<EOF > mysql-reactor.txt
CREATE DATABASE reactor;
CREATE USER 'reactor'@'localhost' IDENTIFIED BY 'p@ssword';
GRANT ALL ON reactor.* TO 'reactor'@'localhost';
CREATE USER 'reactor'@'%' IDENTIFIED BY 'p@ssword';
GRANT ALL ON reactor.* TO 'reactor'@'%';
EOF
mysql -u root < mysql-reactor.txt

wget "https://raw.githubusercontent.com/tascape/reactor/master/src/main/resources/db/reactor.sql" -O reactor.sql
mysql -u reactor -pp@ssword reactor < reactor.sql
service mysql restart

(crontab -l 2>/dev/null; echo "*/17 * * * * mysqldump -u root --no-create-info reactor > /home/vagrant/.reactor/reactor-data.sql") | crontab -
if [[ -e /home/vagrant/.reactor/reactor-data.sql ]]; then
  echo "restore reactor db"
  mysql -u root reactor < /home/vagrant/.reactor/reactor-data.sql || echo "error restoring reactor db"
fi


echo "install tomee +"
wget "https://raw.githubusercontent.com/tascape/reactor-report/master/doc/tomee.sh" -O tomee.sh
bash tomee.sh


echo "install git maven nginx"
apt-get install -y --force-yes git maven nginx apache2-utils tree
echo "server {listen 8088;root /home/vagrant/.reactor;index index.html index.htm;autoindex on;autoindex_localtime on; location /rr/ {proxy_pass http://127.0.0.1:8080/rr/;}}" > reactor-logs
touch /home/vagrant/.reactor/index.html
mv reactor-logs /etc/nginx/sites-enabled/reactor-logs
service nginx restart
